### ISSUE TITLE
Falta parseo del json en post.

### ISSUE THREAD

**Issue by CrisRPia** [jorge-melnik/persona#1]
Nuestro equipo tuvo problemas al leer los usuarios que creamos exitosamente mediante el post. Esto se debe a que el backend no guarda a los mismos como objetos, sino que directamente como strings. Por esto, se dificulta parsear la respuesta al objeto que nos sirve para presentar los usuarios. Podríamos extraer la string y parsear sus contenidos, pero esto claramente no era la intención del ejercicio ya que el array en memoria por defecto tiene un objeto, no una string. Pudimos arreglar esto modificando la siguiente línea:

```javascript
      // backend/src/routes/persona/index.ts:27
      const personaPost = JSON.parse(request.body as string) as PersonaType;
```

Pedimos que implemente este cambio en el repo (idk si puedo hacer pull request sin ser colaborador).

**Comment by jorge-melnik** [comment]
Bien ahí Cristian. 
Faltó agregar el header content-type en la petición. Con eso ya solucionarías el problema sin tocar el backend. 
Actualicé la letra y avisé en el foro, pero acá tb te dejo el ejemplo:
![imagen](https://github.com/user-attachments/assets/0b16c93c-3330-4813-8d41-b7872db04b9e)

Saludos.
